//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWeb.LayerEdit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LayerEdit.ILayerEdit")]
    public interface ILayerEdit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerEdit/addFeatures", ReplyAction="http://tempuri.org/ILayerEdit/addFeaturesResponse")]
        string addFeatures(string adds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILayerEdit/addFeatures", ReplyAction="http://tempuri.org/ILayerEdit/addFeaturesResponse")]
        System.Threading.Tasks.Task<string> addFeaturesAsync(string adds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILayerEditChannel : ClientWeb.LayerEdit.ILayerEdit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LayerEditClient : System.ServiceModel.ClientBase<ClientWeb.LayerEdit.ILayerEdit>, ClientWeb.LayerEdit.ILayerEdit {
        
        public LayerEditClient() {
        }
        
        public LayerEditClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LayerEditClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LayerEditClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LayerEditClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addFeatures(string adds) {
            return base.Channel.addFeatures(adds);
        }
        
        public System.Threading.Tasks.Task<string> addFeaturesAsync(string adds) {
            return base.Channel.addFeaturesAsync(adds);
        }
    }
}
